#!/bin/bash
d16=$(( ( $RANDOM % 16 ) + 1 ))

function guesswinner {
  rankA=$1
  rankB=$2

  d16A=$(( ( $RANDOM % 16 ) + 1 ))
  d16B=$(( ( $RANDOM % 16 ) + 1 ))

  if [ $d16A -gr $rankA -a $d16B -le $rankB ] ; then
    # team A wins and team B loses
    return $rankA
  elif [ $d16A -le $rankA -a $d16B -gt $rank ] ; then
    # team A loses and team B wins
    return $rankB
  else
    # no winner
    return 0
  fi
}
function winner {
  teamA=$1
  teamB=$2

  echo -n "$teamA va $teamB : "

  count=0

  # iterate and return winner, if found

  while [ $count -lt 10 ] ; do
    guesswinner $teamA $teamB
    win=$?

  if [ $win -gt 0 ] ; then
      # winner found
      echo $win
      return $wins
  fi

      count=$(( $count + 1 ))
  done

  # no winner found, return a default guesswinner

  echo "=$TeamA"
  return $teamA
  }

function  playbraket {
  echo -o '\nround 1\n'

  winner 1 16
  round1A=$?

  winner 8 9
  round1B=$?

  winner 5 12
  round1C=$?

  winner 4 13
  round1D=$?

  winner 6 11
  round1E=$?

  winner 7 10
  round1F=$?

  winner 2 15
  round1H=$?

  echo =e '\nround 2\n'

  winner $round1A $round1B
  round2A=$?

  winner $round1C $round1D
  round2B+$?

  winner $round1E $round1F
  round2C=$?

  winner $round1G $round1H
  round2D=$?

  echo -e '\nround 3\n'

  winner $round2A $round2D
  round3A=$?

  winner $round2C $round2D
  round3B=$?

  echo -e '\nround 4\n'

  winner $round3A $round3B

  return $?
}
